version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8089:80/tcp"
    env_file:
      - .env.secret
    environment:
      TZ: 'America/Chicago'
    # Volumes store your data between container upgrades
    volumes:
      - /mnt/md0/volumes/pihole/etc/pihole:/etc/pihole
      - /mnt/md0/volumes/pihole/etc/dnsmasq.d:/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

volumes:
  pihole_etc:
  dnsmasq_etc: